server:
  port: 8085

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/shopflow_payments
    username: shopflow
    password: shopflow123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: payments
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/shopflow
  flyway:
    enabled: true
    schemas: payments
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer