server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/shopflow_orders
    username: shopflow
    password: shopflow123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: orders
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/shopflow
  flyway:
    enabled: true
    schemas: orders
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
